version: "2"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=datadb
      - MYSQL_USER=czfureczka
      - MYSQL_PASSWORD=pass123
    ports:
      - 4302:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  web:
    build:
      context: ./web
    ports:
      - 4300:8080
      - 4301:9990
    depends_on:
      - db
    links:
      - db
    dns: 8.8.8.8
