<!DOCTYPE html>
<html>
<title>Szybko do celu</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<body class="w3-content w3-white" style="max-width:100%; background-color: black !important;">

<header class="w3-display-container mx-auto">

    <div class="mySlides w3-animate-opacity ">
        <img class="w3-image" src="/image/background.jpg" alt="Image 1" style="min-width:90%" >
        <div class="w3-display-middle" style="width:45%">
            <div class="w3-black w3-opacity w3-hover-opacity-off w3-padding-large w3-round-large">
                <h1 class="w3-xlarge "><b>Witaj w aplikacji "Szybko do Celu"!</b></h1>
                <hr class="w3-opacity ">
                <p><b>Dziś na pewno dojedziesz na czas!</b></p>
                <a href="http://czfureczka.jjdd6.is-academy.pl/menu" class="w3-button w3-block w3-white w3-round"
                   onclick="document.getElementById('download').style.display='block'"><b>SZYBKI START</b></i></button></a>
                <br>
                <a href="http://czfureczka.jjdd6.is-academy.pl/googlelogin" class="w3-button w3-block w3-white w3-round"
                   onclick="document.getElementById('download').style.display='block'"><b>ZALOGUJ</b></i></button></a>
            </div>
        </div>
    </div>
